chartConfig:
  config:
    columns: {}
    conditionalFormattings: []
    hideRowNumbers: false
    metricsAsRows: false
    showColumnCalculation: true
    showResultsTotal: false
    showRowCalculation: false
    showSubtotals: false
    showTableNames: false
  type: table
contentType: chart
description: Average order value split by acquisition source
metricQuery:
  additionalMetrics: []
  dimensions:
  - orders_order_source
  exploreName: orders
  filters: {}
  limit: 500
  metricOverrides: {}
  metrics:
  - orders_average_order_size
  sorts:
  - descending: false
    fieldId: orders_order_source
  tableCalculations: []
  timezone: project_timezone
name: Average Order Size by Source
slug: avg-order-size-by-source
spaceSlug: jaffle-shop
tableConfig:
  columnOrder:
  - orders_order_source
  - orders_average_order_size
tableName: orders
verification: null
version: 1
